
   name: Build and Test Java Spring Boot Application 
    
   on:
     push:
       branches: [ "main" ]
     pull_request:
       branches: [ "main" ]
    
   jobs:
     build:
       runs-on: ubuntu-latest
       steps:
         - name: 'Checkout GitHub Action'
           uses: actions/checkout@v3
         - name: Set up JDK 17
           uses: actions/setup-java@v3
           with:
             java-version: '17'
             distribution: 'temurin'
             cache: maven
         
         - name: Compile with Maven
           run: mvn compile
         - name: Upload Compilation Artifacts
           uses: actions/upload-artifact@v4
           with:
             name: comiled-artifacts
             path: target/classes/

   
     test:
       runs-on: ubuntu-latest
       needs: build
       steps:
         - name: 'Checkout GitHub Action'
           uses: actions/checkout@v3
           
         - name: Set up JDK 17
           uses: actions/setup-java@v3
           with:
             java-version: '17'
             distribution: 'temurin'
             cache: maven
   
         - name: Run tests
           run: mvn test

         - name: Upload Test Report
           uses: actions/upload-artifact@v4
           if: success() || failure()
           with:
             name: test report
             path: target/surefire-reports/

     deploy:
       runs-on: ubuntu-latest
       needs: test
       steps:
         - uses: actions/checkout@v3
         - name: Set up JDK 17
           uses: actions/setup-java@v3
           with:
             java-version: '17'
             distribution: 'temurin'
             cache: maven
         - name: Build with Maven
           run: mvn package -DskipTests
             - name: Deploy to Azure WebApp
               uses: azure/webapps-deploy@v2
               with:
                 app-name: nombre App Service
                 publish-profile: secreto creado en GitHub
                 package:  nombre archivo .jar

