
   name: Build and Test Java Spring Boot Application 
    
   on:
     push:
       branches: [ "main" ]
     pull_request:
       branches: [ "main" ]
    
   jobs:
     build:
       runs-on: ubuntu-latest
       steps:
         - name: 'Checkout GitHub Action'
           uses: actions/checkout@v3
         - name: Set up JDK 17
           uses: actions/setup-java@v3
           with:
             java-version: '17'
             distribution: 'temurin'
             cache: maven
         
         - name: Build with Maven
           run: mvn compile
   
     test:
       runs-on: ubuntu-latest
       needs: build
       steps:
         - name: 'Checkout GitHub Action'
           uses: actions/checkout@v3
           
         - name: Set up JDK 17
           uses: actions/setup-java@v3
           with:
             java-version: '17'
             distribution: 'temurin'
             cache: maven
   
         - name: Run tests
           run: mvn verify
   
     deploy:
       runs-on: ubuntu-latest
       needs: test
       steps:
         - name: 'Checkout GitHub Action'  
           uses: actions/checkout@v3
           
         - name: Set up JDK 17
           uses: actions/setup-java@v3
           with:
             java-version: '17'
             distribution: 'temurin'
             cache: maven
         - name: Build with Maven
           run: echo "En construccion..."

